DROP TABLE IF EXISTS Address;
DROP TABLE IF EXISTS Person;

CREATE TABLE Person (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    identification VARCHAR(100) NOT NULL
);

CREATE TABLE Address (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    country VARCHAR(20) NOT NULL,
    county VARCHAR(20) NOT NULL.
    city VARCHAR(20) NOT NULL
    postcode VARCHAR(20) NOT NULL
    streetAddress VARCHAR(20) NOT NULL,
    phoneNumber INTEGER NOT NULL
);
